services:
  api:
    build: .
    container_name: web_api
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql_server2024
    ports:
      - "1433:1433"